### ISSUE TITLE
raspberry pi 2+ and 3 version? 

### ISSUE THREAD

**Issue by schlichtanders** [joewalnes/pi-crust#3]
This project sounds awesome, however the board seems to fit to the old raspberry pi version only

Any plans to put this to the next level for never raspberry pi versions?

**Comment by shawaj** [comment]
We've got a design but just have not released it yet as we've been too busy.

But we will get it out of the door soon.

Thanks

**Comment by schlichtanders** [comment]
that sounds great!!
looking forward to it

**Comment by shawaj** [comment]
Yep, looking at it today. See what needs sorting before manufacture :-)

**Comment by shawaj** [comment]
Have fixed this with https://github.com/joewalnes/pi-crust/commit/4fd7ba9fa64b0fee1ba657ba59e217d132ff00e8

Will be starting to produce these in the next month or so. And then will release via https://www.pi-supply.com

**Comment by shawaj** [comment]
Closing this issue now - but keep an eye on our twitter feed :-)

[https://twitter.com/PiSupply/status/852243668845174784](https://twitter.com/PiSupply/status/852243668845174784)
